### ISSUE TITLE
collation_server and chatacter_set_client settings are ignored

### ISSUE THREAD

**Issue by activedecay** [mrlesmithjr/ansible-mysql#16]
changing these settings in user-consumed playbooks is ignored. potentially fix it by removing the comments from the mysql cnf file
```
#character_set_client = {{ mysql_settings['character_set_client'] }}
#collation_server = {{ mysql_settings['collation_server'] }}
```

**Comment by mrlesmithjr** [comment]
@activedecay I'll take a look into resolving this soon.
